primaries_shortcuts = {'1a': 'small cell lung cancer',
                        '1b': 'squamous cell lung cancer',
                        '1c': 'adenocarcinoma of the lung',
                        '1d': 'large cell lung cancer',
                        '1e': 'lung cancer, other',
                        '1f': 'lung cancer, exact histology unknown',
                        '1g': 'NSCLC',
                        '2': 'breast cancer',
                        '3': 'melanoma',
                        '4': 'prostate cancer',
                        '5': 'renal cell carcinoma',
                        '6': 'transitional cell carcinoma', # also called urothelial carcinoma
                        '7': 'colorectal cancer',
                        '8': 'plasmacytoma',
                        '9': 'testicular cancer',
                        '10': 'thyroid cancer',
                        '11': 'laryngeal cancer',
                        '12': 'cervical cancer',
                        '13': 'cholangiocellular carcinoma',
                        '14': 'ovarian cell carcinoma',
                        '15': 'rhabdomyosarcoma',
                        '16': 'gastric cancer',
                        '17': 'endometrial cancer',
                        '18': 'osteosarcoma',
                        '20': 'esophageal cancer',
                        '21': 'oral squamous cell carcinoma',
                        '22': 'synovial cell carcinoma',
                        '23': 'leiomyosarcoma',
                        '24': 'vulvar carcinoma',
                        '25': 'salivary gland cancer',
                        '26': 'cancer of unknown primary',
                        '27': 'pancreatic cancer'}