primaries_shortcuts_brats = { '1a': 'small cell lung cancer',
                        '1b': 'squamous cell lung cancer',
                        '1c': 'adenocarcinoma of the lung',
                        '1d': 'large cell lung cancer',
                        '1e': 'lung cancer, other',
                        '1f': 'lung cancer, exact histology unknown',
                        '1g': 'NSCLC',
                        '2': 'breast cancer',
                        '3': 'melanoma',
                        '4': 'prostate cancer',
                        '5': 'renal cell carcinoma',
                        '6': 'transitional cell carcinoma', # also called urothelial carcinoma
                        '7': 'colorectal cancer',
                        '8': 'plasmacytoma',
                        '9': 'testicular cancer',
                        '10': 'thyroid cancer',
                        '11': 'laryngeal cancer',
                        '12': 'cervical cancer',
                        '13': 'cholangiocellular carcinoma',
                        '14': 'ovarian cell carcinoma',
                        '15': 'rhabdomyosarcoma',
                        '16': 'gastric cancer',
                        '17': 'endometrial cancer',
                        '18': 'osteosarcoma',
                        '20': 'esophageal cancer',
                        '21': 'oral squamous cell carcinoma',
                        '22': 'synovial cell carcinoma',
                        '23': 'leiomyosarcoma',
                        '24': 'vulvar carcinoma',
                        '25': 'salivary gland cancer',
                        '26': 'cancer of unknown primary',
                        '27': 'pancreatic cancer'}

cancer_primaries_dict = { '1a': 'small cell lung cancer',
                            '1b': 'squamous cell lung cancer',
                            '1c': 'adenocarcinoma of the lung',
                            '1d': 'large cell lung cancer',
                            '1e': 'NSCLC',
                            '1e': 'lung cancer, other',
                            '1g': 'lung cancer, exact histology unknown',
                            '2': 'breast cancer',
                            '3': 'prostate cancer',
                            '4': 'testicular cancer',
                            '5': 'renal cell carcinoma',
                            '6': 'transitional cell carcinoma', # also called urothelial carcinoma
                            '7': 'vulvar carcinoma',
                            '8': 'cervical cancer',
                            '9': 'endometrial cancer',
                            '10': 'ovarian cell carcinoma',
                            '11a': 'osteosarcoma',
                            '11b': 'liposarcome',
                            '11c': 'leiomyosarcoma',
                            '11d': 'rhabdomyosarcoma',
                            '11e': 'synovial sarcoma',
                            '11f': 'sarcoma, other',
                            '11g': 'sarcoma, exact histology unknown',
                            '12': 'melanoma',
                            '13': 'salivary gland cancer',
                            'x': 'XXXXXXXXX',
                            '15': 'oral squamous cell carcinoma',
                            '16': 'laryngeal cancer',
                            '17': 'thyroid cancer',
                            '18': 'esophageal cancer',
                            '19': 'gastric cancer',
                            '20': 'pancreatic cancer',
                            '21': 'cholangiocellular carcinoma',
                            '22': 'colorectal cancer',
                            '23': 'plasmacytoma',
                            '24': 'cancer of unknown primary'
}